# Generated by Django 3.2.4 on 2021-07-24 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20210713_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 31, 41, 583302, tzinfo=utc), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 31, 41, 583809, tzinfo=utc), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 31, 41, 583830, tzinfo=utc), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
