# Generated by Django 3.2.4 on 2021-07-25 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210724_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 8, 24, 4, 175441, tzinfo=utc), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 8, 24, 4, 175466, tzinfo=utc), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 8, 24, 4, 174809, tzinfo=utc), verbose_name='дата создания'),
        ),
    ]
