# Generated by Django 3.2.4 on 2021-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses_and_apartments', '0002_auto_20210713_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='cost_dollar',
            field=models.FloatField(default=2.5136, verbose_name='курс доллара'),
        ),
        migrations.AlterField(
            model_name='saleflat',
            name='cost_dollar',
            field=models.FloatField(default=2.5136, verbose_name='курс доллара'),
        ),
    ]
