# Generated by Django 3.2.4 on 2021-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses_and_apartments', '0003_auto_20210725_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='cost_dollar',
            field=models.FloatField(default=2.514, verbose_name='курс доллара'),
        ),
        migrations.AlterField(
            model_name='saleflat',
            name='cost_dollar',
            field=models.FloatField(default=2.514, verbose_name='курс доллара'),
        ),
    ]
